### ISSUE TITLE
Codegen: emit .js and .d.ts code for collections

### ISSUE THREAD

**Issue by minenwerfer** [aeria-org/aeria#207]

**Comment by Cephas369** [comment]
Started doing the d.ts code generator, there is still some refactors to do before going to the .js code

https://github.com/Cephas369/aeria/commit/45e14ffde9659a79b5fa794b211a4db50f36e188

**Comment by Cephas369** [comment]
Finished javascript code generator, as every collection code is being generated in one file i made the import symbols of the aeria collections to be renamed to original### to avoid name duplications
